[package]
name = "token_search"
version = "0.2.0"
authors = ["Joshua Clayton <joshua.clayton@gmail.com>"]
edition = "2024"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.1"
codebase_files = { path = "../../crates/codebase_files" }
indicatif = { workspace = true }
itertools = { workspace = true }
nom = { workspace = true }
rayon = { workspace = true }
read_ctags = { path = "../../crates/read_ctags" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
