[package]
name = "token_analysis"
version = "0.1.0"
authors = ["Joshua Clayton <joshua.clayton@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
token_search = { path = "../../crates/token_search/" }
read_ctags = { path = "../../crates/read_ctags/" }
project_configuration = { path = "../../crates/project_configuration/" }
serde_json = { workspace = true }
serde = { workspace = true }
itertools = { workspace = true }
rayon = { workspace = true }
indicatif = { workspace = true }

[dev-dependencies]
totems = { workspace = true }
