[package]
name = "cli"
version = "0.4.0"
authors = ["Joshua Clayton <joshua.clayton@gmail.com>"]
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
codebase_files = { path = "../../crates/codebase_files/" }
colored = "3.1"
dirs-next = "2.0"
itertools = { workspace = true }
project_configuration = { path = "../../crates/project_configuration/" }
read_ctags = { path = "../../crates/read_ctags/" }
serde_json = { workspace = true }
token_analysis = { path = "../../crates/token_analysis/" }
token_search = { path = "../../crates/token_search/" }
