[package]
name = "project_configuration"
version = "0.1.0"
authors = ["Joshua Clayton <joshua.clayton@gmail.com>"]
edition = "2024"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.11"
nom = { workspace = true }
serde = { workspace = true }
serde_yaml = "0.9"
token_search = { path = "../../crates/token_search" }

[dev-dependencies]
proptest = { workspace = true }
totems = { workspace = true }
