#![deny(missing_docs)]

//! `read_ctags` is a crate for parsing `tags` files generated by [Universal Ctags](https://ctags.io/).
//!
//! The Universal Ctags implementation includes support for different kinds of tokens, enabling a
//! richer set of information, as well as (based on the language) information around visibility,
//! the class it belongs to, and more.
//!
//! # Examples
//!
//! This would allow for generating a JSON representation of a tags file:
//!
//! ```
//! use read_ctags::TagsReader;
//! use serde_json;
//! match TagsReader::default().load() {
//!   Ok(outcome) => println!("{}", serde_json::to_string(&outcome.tags).unwrap()),
//!   Err(e) => eprintln!("{}", e),
//! }
//! ```

mod ctag_item;
mod language;
mod parser;
mod tag_program;
mod tags_file;
mod tags_reader;
mod token_kind;

pub use self::ctag_item::*;
pub use self::language::*;
pub use self::tag_program::TagProgram;
pub use self::tags_file::*;
pub use self::tags_reader::*;
pub use self::token_kind::*;
